import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const REPORT_CATEGORIES = {
    all: { id: 'all', label: 'Full Report', icon: 'bx-file', description: 'Summary, users, recipes & ingredients' },
    summary: { id: 'summary', label: 'Summary', icon: 'bx-bar-chart-alt-2', description: 'Overview statistics only' },
    users: { id: 'users', label: 'Users', icon: 'bx-group', description: 'User accounts & activity' },
    recipes: { id: 'recipes', label: 'Recipes', icon: 'bx-food-menu', description: 'Recipe listings & details' },
    ingredients: { id: 'ingredients', label: 'Ingredients', icon: 'bx-leaf', description: 'Ingredient database' },
};

export const REPORT_FORMATS = {
    excel: { id: 'excel', label: 'Excel (.xlsx)', icon: 'bx-spreadsheet' },
    pdf: { id: 'pdf', label: 'PDF (.pdf)', icon: 'bx-file-pdf' },
};

const BRAND_COLOR = [207, 153, 108];
const HEADER_COLOR = [30, 41, 59];

/** Only administrators may generate admin reports (PDF/Excel). */
const assertAdminUser = (adminUser) => {
    if (!adminUser || adminUser.role !== 'admin') {
        throw new Error('Access denied. Only administrators can generate reports.');
    }
};

const getDateRange = (timeRange) => {
    const now = new Date();
    const start = new Date();

    if (timeRange === 'week') {
        start.setDate(now.getDate() - 7);
    } else if (timeRange === 'month') {
        start.setMonth(now.getMonth() - 1);
    } else if (timeRange === 'year') {
        start.setFullYear(now.getFullYear() - 1);
    }

    return { start, end: now };
};

const getTimeRangeLabel = (timeRange) =>
    timeRange.charAt(0).toUpperCase() + timeRange.slice(1);

const filterByDateRange = (items, timeRange) => {
    const { start, end } = getDateRange(timeRange);
    return items.filter((item) => {
        const createdDate = new Date(item.createdAt);
        return createdDate >= start && createdDate <= end;
    });
};

const formatDate = (date) =>
    date ? new Date(date).toLocaleDateString('en-PH', { year: 'numeric', month: 'short', day: 'numeric' }) : 'N/A';

const formatDateTime = (date) =>
    new Date(date).toLocaleString('en-PH', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });

const getDaysSinceLogin = (lastLogin) => {
    if (!lastLogin) return 'Never';
    return Math.floor((Date.now() - new Date(lastLogin).getTime()) / (1000 * 60 * 60 * 24));
};

const getShareStatusLabel = (status) => {
    const labels = {
        approved: 'Approved',
        pending: 'Pending',
        rejected: 'Rejected',
        not_shared: 'Not Shared',
    };
    return labels[status] || status;
};

const buildSummaryRows = ({ stats, users, recipes, ingredients, timeRange, adminUser }) => {
    const timeRangeLabel = getTimeRangeLabel(timeRange);
    const { start, end } = getDateRange(timeRange);
    const filteredUsers = filterByDateRange(users, timeRange);
    const filteredRecipes = filterByDateRange(recipes, timeRange);

    const activeUsers = users.filter((u) => {
        if (!u.lastLogin) return false;
        const days = (Date.now() - new Date(u.lastLogin).getTime()) / (1000 * 60 * 60 * 24);
        return days <= 7;
    }).length;

    const adminRecipes = recipes.filter((r) => r.createdBy?.role === 'admin' || r.isPublic).length;
    const userRecipes = recipes.filter((r) => r.createdBy?.role === 'user' && !r.isPublic).length;
    const sharedRecipes = recipes.filter((r) => r.isShared && r.shareStatus === 'approved').length;

    return [
        ['FOODHUB ADMIN SYSTEM REPORT'],
        [`${timeRangeLabel} Overview Report`],
        [`Generated on: ${formatDateTime(new Date())}`],
        [`Generated by: ${adminUser?.name || 'Administrator'} (Admin)`],
        [`Date Range: ${formatDate(start)} - ${formatDate(end)}`],
        [''],
        ['OVERALL STATISTICS'],
        ['Metric', 'Value'],
        ['Total Users', stats.totalUsers],
        ['Total Recipes', stats.totalRecipes],
        ['Pending Recipes', stats.pendingRecipes],
        ["Today's Logins", stats.todayLogins],
        ['Total Ingredients', ingredients?.length || 0],
        [''],
        [`${timeRangeLabel.toUpperCase()} DATA`],
        ['Metric', 'Value'],
        [`New Users (${timeRangeLabel})`, filteredUsers.length],
        [`New Recipes (${timeRangeLabel})`, filteredRecipes.length],
        [''],
        ['RECIPE BREAKDOWN'],
        ['Type', 'Count'],
        ['Admin Recipes', adminRecipes],
        ['User Recipes', userRecipes],
        ['Community Shared', sharedRecipes],
        [''],
        ['USER ENGAGEMENT'],
        ['Status', 'Count'],
        ['Active Users (7 days)', activeUsers],
        ['Inactive Users', users.length - activeUsers],
        [''],
        ['RECIPE STATUS BREAKDOWN'],
        ['Status', 'Count'],
        ['Approved', recipes.filter((r) => r.shareStatus === 'approved').length],
        ['Pending', recipes.filter((r) => r.shareStatus === 'pending').length],
        ['Rejected', recipes.filter((r) => r.shareStatus === 'rejected').length],
        ['Not Shared', recipes.filter((r) => r.shareStatus === 'not_shared').length],
    ];
};

const buildUsersRows = ({ users, timeRange }) => {
    const timeRangeLabel = getTimeRangeLabel(timeRange);
    const displayUsers = filterByDateRange(users, timeRange);

    const rows = [
        [`USERS REPORT - ${timeRangeLabel} Data`],
        [''],
        ['Name', 'Email', 'Role', 'Status', 'Verified', 'Created At', 'Last Login', 'Days Since Login'],
    ];

    displayUsers.forEach((user) => {
        rows.push([
            user.name,
            user.email,
            (user.role || 'user').toUpperCase(),
            user.status === 'active' ? 'Active' : user.status || 'Inactive',
            user.isVerified ? 'Yes' : 'No',
            formatDate(user.createdAt),
            user.lastLogin ? formatDate(user.lastLogin) : 'Never',
            getDaysSinceLogin(user.lastLogin),
        ]);
    });

    rows.push([''], [`Total Users: ${displayUsers.length}`]);
    return rows;
};

const buildRecipesRows = ({ recipes, timeRange }) => {
    const timeRangeLabel = getTimeRangeLabel(timeRange);
    const displayRecipes = filterByDateRange(recipes, timeRange);

    const rows = [
        [`RECIPES REPORT - ${timeRangeLabel} Data`],
        [''],
        ['Title', 'Category', 'Cuisine', 'Created By', 'Type', 'Status', 'Cooking Time', 'Difficulty', 'Rating', 'Created At'],
    ];

    displayRecipes.forEach((recipe) => {
        rows.push([
            recipe.title || recipe.name || 'Untitled',
            recipe.category || 'N/A',
            recipe.cuisine || 'N/A',
            recipe.createdBy?.name || 'Unknown',
            recipe.isPublic ? 'Admin' : 'User',
            getShareStatusLabel(recipe.shareStatus),
            recipe.cookingTime ? `${recipe.cookingTime} mins` : 'N/A',
            recipe.difficulty || 'N/A',
            recipe.averageRating ? recipe.averageRating.toFixed(1) : '0',
            formatDate(recipe.createdAt),
        ]);
    });

    rows.push([''], [`Total Recipes: ${displayRecipes.length}`]);
    return rows;
};

const buildIngredientsRows = ({ ingredients }) => {
    const rows = [
        ['INGREDIENTS DATABASE REPORT'],
        [''],
        ['#', 'Ingredient Name', 'ID'],
    ];

    (ingredients || []).forEach((ingredient, index) => {
        rows.push([index + 1, ingredient.name, ingredient._id]);
    });

    rows.push([''], [`Total Ingredients: ${ingredients?.length || 0}`]);
    return rows;
};

const getSheetsForCategory = (category, data) => {
    const sheets = [];

    const addSheet = (name, rows, cols) => {
        sheets.push({ name, rows, cols });
    };

    const categories = category === 'all'
        ? ['summary', 'users', 'recipes', 'ingredients']
        : [category];

    categories.forEach((cat) => {
        switch (cat) {
            case 'summary':
                addSheet('Summary', buildSummaryRows(data), [{ wch: 30 }, { wch: 20 }]);
                break;
            case 'users':
                addSheet('Users', buildUsersRows(data), [
                    { wch: 20 }, { wch: 30 }, { wch: 10 }, { wch: 12 },
                    { wch: 10 }, { wch: 15 }, { wch: 15 }, { wch: 18 },
                ]);
                break;
            case 'recipes':
                addSheet('Recipes', buildRecipesRows(data), [
                    { wch: 30 }, { wch: 15 }, { wch: 15 }, { wch: 20 },
                    { wch: 10 }, { wch: 12 }, { wch: 12 }, { wch: 10 }, { wch: 8 }, { wch: 15 },
                ]);
                break;
            case 'ingredients':
                if (data.ingredients?.length > 0) {
                    addSheet('Ingredients', buildIngredientsRows(data), [
                        { wch: 8 }, { wch: 40 }, { wch: 30 },
                    ]);
                }
                break;
            default:
                break;
        }
    });

    return sheets;
};

const getCategoryTitle = (category) => REPORT_CATEGORIES[category]?.label || 'Report';

const getFileName = (category, format, timeRange) => {
    const date = new Date().toISOString().split('T')[0];
    const timeLabel = getTimeRangeLabel(timeRange);
    const categoryLabel = category === 'all' ? 'Full' : getCategoryTitle(category);
    const ext = format === 'pdf' ? 'pdf' : 'xlsx';
    return `FoodHub_Admin_${categoryLabel}_${timeLabel}_Report_${date}.${ext}`;
};

export const exportReportToExcel = ({ adminUser, category, timeRange, stats, users, recipes, ingredients }) => {
    assertAdminUser(adminUser);

    const data = { stats, users, recipes, ingredients, timeRange, adminUser };
    const sheets = getSheetsForCategory(category, data);

    if (sheets.length === 0) {
        throw new Error('No data available for the selected category.');
    }

    const wb = XLSX.utils.book_new();

    sheets.forEach(({ name, rows, cols }) => {
        const sheet = XLSX.utils.aoa_to_sheet(rows);
        sheet['!cols'] = cols;
        XLSX.utils.book_append_sheet(wb, sheet, name);
    });

    const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([excelBuffer], {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });

    saveAs(blob, getFileName(category, 'excel', timeRange));
};

const addPdfHeaderFooter = (doc, reportTitle, categoryLabel, timeRangeLabel, adminUser) => {
    const pageCount = doc.internal.getNumberOfPages();
    const adminName = adminUser?.name || 'Administrator';

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        // Header background
        doc.setFillColor(...BRAND_COLOR);
        doc.rect(0, 0, pageWidth, 32, 'F');

        // Header text
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('FOODHUB ADMIN REPORT', 14, 12);

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.text(`${categoryLabel} | ${timeRangeLabel} Period | Admin Only`, 14, 20);

        doc.setFontSize(8);
        doc.text(reportTitle, pageWidth - 14, 10, { align: 'right' });
        doc.text(`Generated by: ${adminName}`, pageWidth - 14, 17, { align: 'right' });
        doc.text(`Date: ${formatDateTime(new Date())}`, pageWidth - 14, 24, { align: 'right' });

        // Footer line
        doc.setDrawColor(...BRAND_COLOR);
        doc.setLineWidth(0.5);
        doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);

        // Footer text
        doc.setTextColor(100, 116, 139);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(`FoodHub Admin Dashboard - Confidential | Issued by ${adminName}`, 14, pageHeight - 10);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
    }
};

const rowsToTableData = (rows) => {
    // Find header row (first row with multiple columns after title rows)
    let headerIndex = -1;
    for (let i = 0; i < rows.length; i++) {
        if (Array.isArray(rows[i]) && rows[i].length > 1) {
            headerIndex = i;
            break;
        }
    }

    if (headerIndex === -1) {
        return { head: [], body: rows.filter((r) => r.length > 0) };
    }

    const head = [rows[headerIndex]];
    const body = rows.slice(headerIndex + 1).filter(
        (row) => row.length > 1 && !String(row[0]).startsWith('Total')
    );

    return { head, body };
};

export const exportReportToPDF = ({ adminUser, category, timeRange, stats, users, recipes, ingredients }) => {
    assertAdminUser(adminUser);

    const data = { stats, users, recipes, ingredients, timeRange, adminUser };
    const sheets = getSheetsForCategory(category, data);

    if (sheets.length === 0) {
        throw new Error('No data available for the selected category.');
    }

    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const timeRangeLabel = getTimeRangeLabel(timeRange);
    const categoryLabel = getCategoryTitle(category);
    const reportTitle = `FoodHub Admin ${categoryLabel} Report`;

    sheets.forEach((sheet, sheetIndex) => {
        if (sheetIndex > 0) {
            doc.addPage();
        }

        const { head, body } = rowsToTableData(sheet.rows);

        // Section title for multi-sheet reports
        if (sheets.length > 1) {
            doc.setTextColor(...HEADER_COLOR);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text(sheet.name, 14, 41);
        }

        if (head.length > 0 && body.length > 0) {
            autoTable(doc, {
                startY: sheets.length > 1 ? 45 : 38,
                head,
                body,
                theme: 'grid',
                headStyles: {
                    fillColor: BRAND_COLOR,
                    textColor: [255, 255, 255],
                    fontStyle: 'bold',
                    fontSize: 8,
                },
                bodyStyles: {
                    fontSize: 7,
                    textColor: HEADER_COLOR,
                },
                alternateRowStyles: {
                    fillColor: [248, 249, 250],
                },
                margin: { top: 38, bottom: 25, left: 14, right: 14 },
                styles: {
                    overflow: 'linebreak',
                    cellPadding: 2,
                },
            });
        } else {
            // Summary-style key-value rows
            const summaryBody = sheet.rows.filter((row) => row.length === 2 && row[0] && row[1] !== undefined);
            const titleRows = sheet.rows.filter((row) => row.length === 1 && row[0]);

            let startY = 38;
            titleRows.forEach((row) => {
                const isMainTitle = row[0].includes('FOODHUB') || row[0].includes('REPORT');
                doc.setFontSize(isMainTitle ? 11 : 9);
                doc.setFont('helvetica', isMainTitle ? 'bold' : 'normal');
                doc.setTextColor(...(isMainTitle ? HEADER_COLOR : [100, 116, 139]));
                doc.text(row[0], 14, startY);
                startY += 7;
            });

            if (summaryBody.length > 0) {
                autoTable(doc, {
                    startY: startY + 2,
                    body: summaryBody,
                    theme: 'plain',
                    bodyStyles: { fontSize: 8, textColor: HEADER_COLOR },
                    columnStyles: {
                        0: { fontStyle: 'bold', cellWidth: 80 },
                        1: { cellWidth: 60 },
                    },
                    margin: { top: 38, bottom: 25, left: 14, right: 14 },
                });
            }
        }
    });

    addPdfHeaderFooter(doc, reportTitle, categoryLabel, timeRangeLabel, adminUser);
    doc.save(getFileName(category, 'pdf', timeRange));
};

export const generateReport = async ({ adminUser, category, format, timeRange, stats, users, recipes, ingredients }) => {
    assertAdminUser(adminUser);

    const options = { adminUser, category, timeRange, stats, users, recipes, ingredients };

    if (format === 'pdf') {
        exportReportToPDF(options);
    } else {
        exportReportToExcel(options);
    }
};
